<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MessagePack" Version="3.1.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NightHeaven.Core\NightHeaven.Core.csproj" />
        <ProjectReference Include="..\NightHeaven.Hosting\NightHeaven.Hosting.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="NightHeaven.Tests" />
    </ItemGroup>

</Project>
