[[expansion]]
id = 0
name = "None"
client_flags = "None"
supported_features = "ExpansionNone"
character_list_flags = "ExpansionNone"
housing_flags = "None"
map_selection_flags = "Felucca"
mobile_status_version = 3
required_client_version = ""

[[expansion]]
id = 1
name = "The Second Age"
client_flags = "Felucca"
supported_features = "ExpansionT2A"
character_list_flags = "ExpansionT2A"
housing_flags = "None"
map_selection_flags = "Felucca, Trammel"
mobile_status_version = 3
required_client_version = ""

[[expansion]]
id = 2
name = "Renaissance"
client_flags = "Trammel"
supported_features = "ExpansionUor"
character_list_flags = "ExpansionUor"
housing_flags = "None"
map_selection_flags = "Felucca, Trammel"
mobile_status_version = 3
required_client_version = ""

[[expansion]]
id = 3
name = "Third Dawn"
client_flags = "Ilshenar"
supported_features = "ExpansionUotd"
character_list_flags = "ExpansionUotd"
housing_flags = "None"
map_selection_flags = "Felucca, Trammel, Ilshenar"
mobile_status_version = 3
required_client_version = ""

[[expansion]]
id = 4
name = "Blackthorn's Revenge"
client_flags = "Ilshenar"
supported_features = "ExpansionLbr"
character_list_flags = "ExpansionLbr"
housing_flags = "None"
map_selection_flags = "Felucca, Trammel, Ilshenar"
mobile_status_version = 3
required_client_version = ""

[[expansion]]
id = 5
name = "Age of Shadows"
client_flags = "Malas"
supported_features = "ExpansionAos"
character_list_flags = "ExpansionAos"
housing_flags = "HousingAos"
map_selection_flags = "Felucca, Trammel, Ilshenar, Malas"
mobile_status_version = 6
required_client_version = ""

[[expansion]]
id = 6
name = "Samurai Empire"
client_flags = "Tokuno"
supported_features = "ExpansionSe"
character_list_flags = "ExpansionSe"
housing_flags = "HousingSe"
map_selection_flags = "Felucca, Trammel, Ilshenar, Malas, Tokuno"
mobile_status_version = 6
required_client_version = ""

[[expansion]]
id = 7
name = "Mondain's Legacy"
client_flags = "None"
supported_features = "ExpansionMl"
character_list_flags = "ExpansionMl"
housing_flags = "HousingMl"
map_selection_flags = "Felucca, Trammel, Ilshenar, Malas, Tokuno"
mobile_status_version = 6
required_client_version = "5.0.0a"

[[expansion]]
id = 8
name = "Stygian Abyss"
client_flags = "TerMur"
supported_features = "ExpansionSa"
character_list_flags = "ExpansionSa"
housing_flags = "HousingSa"
map_selection_flags = "Felucca, Trammel, Ilshenar, Malas, Tokuno, TerMur"
mobile_status_version = 6
required_client_version = ""

[[expansion]]
id = 9
name = "High Seas"
client_flags = "None"
supported_features = "ExpansionHs"
character_list_flags = "ExpansionHs"
housing_flags = "HousingHs"
map_selection_flags = "Felucca, Trammel, Ilshenar, Malas, Tokuno, TerMur"
mobile_status_version = 6
required_client_version = "7.0.9.0"

[[expansion]]
id = 10
name = "Time of Legends"
client_flags = "None"
supported_features = "ExpansionTol"
character_list_flags = "ExpansionTol"
housing_flags = "HousingTol"
map_selection_flags = "Felucca, Trammel, Ilshenar, Malas, Tokuno, TerMur"
mobile_status_version = 6
required_client_version = "7.0.45.65"

[[expansion]]
id = 11
name = "Endless Journey"
client_flags = "None"
supported_features = "ExpansionEj"
character_list_flags = "ExpansionEj"
housing_flags = "HousingEj"
map_selection_flags = "Felucca, Trammel, Ilshenar, Malas, Tokuno, TerMur"
mobile_status_version = 6
required_client_version = "7.0.61.0"
