[[skill]]
id = 0
name = "Alchemy"
title = "Alchemist"
str_scale = 0.0
dex_scale = 0.05
int_scale = 0.05
stat_total = 10.0
str_gain = 0.0
dex_gain = 0.5
int_gain = 0.5
gain_factor = 1.0
profession_skill_name = "Alchemy"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 1
name = "Anatomy"
title = "Biologist"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.15
dex_gain = 0.15
int_gain = 0.7
gain_factor = 1.0
profession_skill_name = "Anatomy"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 2
name = "Animal Lore"
title = "Naturalist"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 1.0
gain_factor = 1.0
profession_skill_name = "AnimalLore"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 3
name = "Item Identification"
title = "Merchant"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 1.0
gain_factor = 1.0
profession_skill_name = "ItemID"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 4
name = "Arms Lore"
title = "Weapon Master"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.75
dex_gain = 0.15
int_gain = 0.1
gain_factor = 1.0
profession_skill_name = "ArmsLore"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 5
name = "Parrying"
title = "Duelist"
str_scale = 0.075
dex_scale = 0.025
int_scale = 0.0
stat_total = 10.0
str_gain = 0.75
dex_gain = 0.25
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Parrying"
primary_stat = "Dexterity"
secondary_stat = "Strength"

[[skill]]
id = 6
name = "Begging"
title = "Beggar"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Begging"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 7
name = "Blacksmithy"
title = "Blacksmith"
str_scale = 0.1
dex_scale = 0.0
int_scale = 0.0
stat_total = 10.0
str_gain = 1.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Blacksmith"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 8
name = "Bowcraft/Fletching"
title = "Bowyer"
str_scale = 0.06
dex_scale = 0.16
int_scale = 0.0
stat_total = 22.0
str_gain = 0.6
dex_gain = 1.6
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Bowcraft"
primary_stat = "Dexterity"
secondary_stat = "Strength"

[[skill]]
id = 9
name = "Peacemaking"
title = "Pacifier"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Peacemaking"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 10
name = "Camping"
title = "Explorer"
str_scale = 0.2
dex_scale = 0.15
int_scale = 0.15
stat_total = 50.0
str_gain = 2.0
dex_gain = 1.5
int_gain = 1.5
gain_factor = 1.0
profession_skill_name = "Camping"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 11
name = "Carpentry"
title = "Carpenter"
str_scale = 0.2
dex_scale = 0.05
int_scale = 0.0
stat_total = 25.0
str_gain = 2.0
dex_gain = 0.5
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Carpentry"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 12
name = "Cartography"
title = "Cartographer"
str_scale = 0.0
dex_scale = 0.075
int_scale = 0.075
stat_total = 15.0
str_gain = 0.0
dex_gain = 0.75
int_gain = 0.75
gain_factor = 1.0
profession_skill_name = "Cartography"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 13
name = "Cooking"
title = "Chef"
str_scale = 0.0
dex_scale = 0.2
int_scale = 0.3
stat_total = 50.0
str_gain = 0.0
dex_gain = 2.0
int_gain = 3.0
gain_factor = 1.0
profession_skill_name = "Cooking"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 14
name = "Detecting Hidden"
title = "Scout"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.4
int_gain = 0.6
gain_factor = 1.0
profession_skill_name = "DetectingHidden"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 15
name = "Discordance"
title = "Demoralizer"
str_scale = 0.0
dex_scale = 0.025
int_scale = 0.025
stat_total = 5.0
str_gain = 0.0
dex_gain = 0.25
int_gain = 0.25
gain_factor = 1.0
profession_skill_name = "Enticement"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 16
name = "Evaluating Intelligence"
title = "Scholar"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 1.0
gain_factor = 1.0
profession_skill_name = "EvaluateIntelligence"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 17
name = "Healing"
title = "Healer"
str_scale = 0.06
dex_scale = 0.06
int_scale = 0.08
stat_total = 20.0
str_gain = 0.6
dex_gain = 0.6
int_gain = 0.8
gain_factor = 1.0
profession_skill_name = "Healing"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 18
name = "Fishing"
title = "Fisherman"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.5
dex_gain = 0.5
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Fishing"
primary_stat = "Dexterity"
secondary_stat = "Strength"

[[skill]]
id = 19
name = "Forensic Evaluation"
title = "Detective"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.2
int_gain = 0.8
gain_factor = 1.0
profession_skill_name = "ForensicEvaluation"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 20
name = "Herding"
title = "Shepherd"
str_scale = 0.1625
dex_scale = 0.0625
int_scale = 0.025
stat_total = 25.0
str_gain = 1.625
dex_gain = 0.625
int_gain = 0.25
gain_factor = 1.0
profession_skill_name = "Herding"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 21
name = "Hiding"
title = "Shade"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.8
int_gain = 0.2
gain_factor = 1.0
profession_skill_name = "Hiding"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 22
name = "Provocation"
title = "Rouser"
str_scale = 0.0
dex_scale = 0.045
int_scale = 0.005
stat_total = 5.0
str_gain = 0.0
dex_gain = 0.45
int_gain = 0.05
gain_factor = 1.0
profession_skill_name = "Provocation"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 23
name = "Inscription"
title = "Scribe"
str_scale = 0.0
dex_scale = 0.02
int_scale = 0.08
stat_total = 10.0
str_gain = 0.0
dex_gain = 0.2
int_gain = 0.8
gain_factor = 1.0
profession_skill_name = "Inscription"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 24
name = "Lockpicking"
title = "Infiltrator"
str_scale = 0.0
dex_scale = 0.25
int_scale = 0.0
stat_total = 25.0
str_gain = 0.0
dex_gain = 2.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Lockpicking"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 25
name = "Magery"
title = "Mage"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.15
stat_total = 15.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 1.5
gain_factor = 1.0
profession_skill_name = "Magery"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 26
name = "Resisting Spells"
title = "Warder"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.25
dex_gain = 0.25
int_gain = 0.5
gain_factor = 1.0
profession_skill_name = "ResistingSpells"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 27
name = "Tactics"
title = "Tactician"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Tactics"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 28
name = "Snooping"
title = "Spy"
str_scale = 0.0
dex_scale = 0.25
int_scale = 0.0
stat_total = 25.0
str_gain = 0.0
dex_gain = 2.5
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Snooping"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 29
name = "Musicianship"
title = "Bard"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.8
int_gain = 0.2
gain_factor = 1.0
profession_skill_name = "Musicianship"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 30
name = "Poisoning"
title = "Assassin"
str_scale = 0.0
dex_scale = 0.04
int_scale = 0.16
stat_total = 20.0
str_gain = 0.0
dex_gain = 0.4
int_gain = 1.6
gain_factor = 1.0
profession_skill_name = "Poisoning"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 31
name = "Archery"
title = "Archer"
str_scale = 0.025
dex_scale = 0.075
int_scale = 0.0
stat_total = 10.0
str_gain = 0.25
dex_gain = 0.75
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Archery"
primary_stat = "Dexterity"
secondary_stat = "Strength"

[[skill]]
id = 32
name = "Spirit Speak"
title = "Medium"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 1.0
gain_factor = 1.0
profession_skill_name = "SpiritSpeak"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 33
name = "Stealing"
title = "Pickpocket"
str_scale = 0.0
dex_scale = 0.1
int_scale = 0.0
stat_total = 10.0
str_gain = 0.0
dex_gain = 1.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Stealing"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 34
name = "Tailoring"
title = "Tailor"
str_scale = 0.0375
dex_scale = 0.1625
int_scale = 0.05
stat_total = 25.0
str_gain = 0.38
dex_gain = 1.63
int_gain = 0.5
gain_factor = 1.0
profession_skill_name = "Tailoring"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 35
name = "Animal Taming"
title = "Tamer"
str_scale = 0.14
dex_scale = 0.02
int_scale = 0.04
stat_total = 20.0
str_gain = 1.4
dex_gain = 0.2
int_gain = 0.4
gain_factor = 1.0
profession_skill_name = "AnimalTaming"
primary_stat = "Strength"
secondary_stat = "Intelligence"

[[skill]]
id = 36
name = "Taste Identification"
title = "Praegustator"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.2
dex_gain = 0.0
int_gain = 0.8
gain_factor = 1.0
profession_skill_name = "TasteIdentification"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 37
name = "Tinkering"
title = "Tinker"
str_scale = 0.05
dex_scale = 0.02
int_scale = 0.03
stat_total = 10.0
str_gain = 0.5
dex_gain = 0.2
int_gain = 0.3
gain_factor = 1.0
profession_skill_name = "Tinkering"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 38
name = "Tracking"
title = "Ranger"
str_scale = 0.0
dex_scale = 0.125
int_scale = 0.125
stat_total = 25.0
str_gain = 0.0
dex_gain = 1.25
int_gain = 1.25
gain_factor = 1.0
profession_skill_name = "Tracking"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 39
name = "Veterinary"
title = "Veterinarian"
str_scale = 0.08
dex_scale = 0.04
int_scale = 0.08
stat_total = 20.0
str_gain = 0.8
dex_gain = 0.4
int_gain = 0.8
gain_factor = 1.0
profession_skill_name = "Veterinary"
primary_stat = "Intelligence"
secondary_stat = "Dexterity"

[[skill]]
id = 40
name = "Swordsmanship"
title = "Swordsman"
str_scale = 0.075
dex_scale = 0.025
int_scale = 0.0
stat_total = 10.0
str_gain = 0.75
dex_gain = 0.25
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Swordsmanship"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 41
name = "Mace Fighting"
title = "Armsman"
str_scale = 0.09
dex_scale = 0.01
int_scale = 0.0
stat_total = 10.0
str_gain = 0.9
dex_gain = 0.1
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "MaceFighting"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 42
name = "Fencing"
title = "Fencer"
str_scale = 0.045
dex_scale = 0.055
int_scale = 0.0
stat_total = 10.0
str_gain = 0.45
dex_gain = 0.55
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Fencing"
primary_stat = "Dexterity"
secondary_stat = "Strength"

[[skill]]
id = 43
name = "Wrestling"
title = "Wrestler"
str_scale = 0.09
dex_scale = 0.01
int_scale = 0.0
stat_total = 10.0
str_gain = 0.9
dex_gain = 0.1
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Wrestling"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 44
name = "Lumberjacking"
title = "Lumberjack"
str_scale = 0.2
dex_scale = 0.0
int_scale = 0.0
stat_total = 20.0
str_gain = 2.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Lumberjacking"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 45
name = "Mining"
title = "Miner"
str_scale = 0.2
dex_scale = 0.0
int_scale = 0.0
stat_total = 20.0
str_gain = 2.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Mining"
primary_stat = "Strength"
secondary_stat = "Dexterity"

[[skill]]
id = 46
name = "Meditation"
title = "Stoic"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Meditation"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 47
name = "Stealth"
title = "Rogue"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Stealth"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 48
name = "Remove Trap"
title = "Trap Specialist"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Disarm"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 49
name = "Necromancy"
title = "Necromancer"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Necromancy"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 50
name = "Focus"
title = "Driven"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Focus"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 51
name = "Chivalry"
title = "Paladin"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Chivalry"
primary_stat = "Strength"
secondary_stat = "Intelligence"

[[skill]]
id = 52
name = "Bushido"
title = "Samurai"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Bushido"
primary_stat = "Strength"
secondary_stat = "Intelligence"

[[skill]]
id = 53
name = "Ninjitsu"
title = "Ninja"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Ninjitsu"
primary_stat = "Dexterity"
secondary_stat = "Intelligence"

[[skill]]
id = 54
name = "Spellweaving"
title = "Arcanist"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Spellweaving"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 55
name = "Mysticism"
title = "Mystic"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Mysticism"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 56
name = "Imbuing"
title = "Artificer"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Imbuing"
primary_stat = "Intelligence"
secondary_stat = "Strength"

[[skill]]
id = 57
name = "Throwing"
title = "Bladeweaver"
str_scale = 0.0
dex_scale = 0.0
int_scale = 0.0
stat_total = 0.0
str_gain = 0.0
dex_gain = 0.0
int_gain = 0.0
gain_factor = 1.0
profession_skill_name = "Throwing"
primary_stat = "Dexterity"
secondary_stat = "Strength"
