<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <Version>0.1.0</Version>
        <Codename>Lilly</Codename>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>Codename</_Parameter1>
            <_Parameter2>$(Codename)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ConsoleAppFramework" Version="5.7.13">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="DryIoc.Microsoft.DependencyInjection" Version="6.2.0"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14"/>
        <PackageReference Include="Serilog" Version="4.3.1"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NightRaven.Core\NightRaven.Core.csproj"/>
        <ProjectReference Include="..\NightRaven.UO.Domain\NightRaven.UO.Domain.csproj"/>
        <ProjectReference Include="..\NightRaven.Hosting\NightRaven.Hosting.csproj"/>
        <ProjectReference Include="..\NightRaven.Network\NightRaven.Network.csproj"/>
        <ProjectReference Include="..\NightRaven.Persistence\NightRaven.Persistence.csproj"/>
        <ProjectReference Include="..\NightRaven.Plugins\NightRaven.Plugins.csproj"/>
        <ProjectReference Include="..\NightRaven.Network.UO\NightRaven.Network.UO.csproj"/>
        <ProjectReference Include="..\NightRaven.Scripting.Lua\NightRaven.Scripting.Lua.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="NightRaven.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\**\*.*" />
        <EmbeddedResource Include="Assets\**\*.*" />
    </ItemGroup>

</Project>
