<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\NightRaven.Plugins\NightRaven.Plugins.csproj"/>
        <ProjectReference Include="..\..\src\NightRaven.Server\NightRaven.Server.csproj"/>
        <ProjectReference Include="..\..\src\NightRaven.Scripting.Lua\NightRaven.Scripting.Lua.csproj"/>
    </ItemGroup>

</Project>
